---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch.arnob.com
  resources:
  - nidejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.arnob.com
  resources:
  - nidejobs/finalizers
  verbs:
  - update
- apiGroups:
  - batch.arnob.com
  resources:
  - nidejobs/status
  verbs:
  - get
  - patch
  - update
